name: Stashit Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - build: linux
          os: ubuntu-latest
          rust: stable
        - build: macos
          os: macos-latest
          rust: stable
    - name: Install Rust
      run: rustup install ${{ matrix.rust }}
    - name: Build
      run: cargo build --release